"""add_community_avatar_banner_and_category

Revision ID: 736505bdf452
Revises: a1b2c3d4e5f6
Create Date: 2025-11-24 11:05:35.728384

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '736505bdf452'
down_revision: Union[str, Sequence[str], None] = 'a1b2c3d4e5f6'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('communities', sa.Column('category_id', sa.UUID(), nullable=True))
    op.add_column('communities', sa.Column('avatar_url', sa.String(length=500), nullable=True))
    op.add_column('communities', sa.Column('banner_url', sa.String(length=500), nullable=True))
    op.create_index(op.f('ix_communities_category_id'), 'communities', ['category_id'], unique=False)
    op.create_foreign_key(None, 'communities', 'community_categories', ['category_id'], ['id'], ondelete='SET NULL')
    # Add is_pinned as nullable first with default value
    op.add_column('posts', sa.Column('is_pinned', sa.Boolean(), nullable=True, server_default='false'))
    # Make it not null after data is populated
    op.alter_column('posts', 'is_pinned', nullable=False, server_default=None)
    op.add_column('posts', sa.Column('pinned_by', sa.String(length=255), nullable=True))
    op.add_column('posts', sa.Column('pinned_at', sa.DateTime(timezone=True), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('posts', 'pinned_at')
    op.drop_column('posts', 'pinned_by')
    op.drop_column('posts', 'is_pinned')
    op.drop_constraint(None, 'communities', type_='foreignkey')
    op.drop_index(op.f('ix_communities_category_id'), table_name='communities')
    op.drop_column('communities', 'banner_url')
    op.drop_column('communities', 'avatar_url')
    op.drop_column('communities', 'category_id')
    # ### end Alembic commands ###
