"""Add community_pins table

Revision ID: a1b2c3d4e5f6
Revises: c7d8e9f0a1b2
Create Date: 2025-11-24 13:35:00.000000

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'a1b2c3d4e5f6'
down_revision: Union[str, Sequence[str], None] = 'c7d8e9f0a1b2'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('community_pins',
    sa.Column('community_id', sa.UUID(), nullable=False),
    sa.Column('post_id', sa.UUID(), nullable=False),
    sa.Column('pinned_by', sa.UUID(), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['community_id'], ['communities.id'], name=op.f('community_pins_community_id_fkey'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['post_id'], ['posts.id'], name=op.f('community_pins_post_id_fkey'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['pinned_by'], ['users.id'], name=op.f('community_pins_pinned_by_fkey'), ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id', name=op.f('community_pins_pkey'))
    )
    op.create_index(op.f('ix_community_pins_community_id'), 'community_pins', ['community_id'], unique=False)
    op.create_index(op.f('ix_community_pins_post_id'), 'community_pins', ['post_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_community_pins_post_id'), table_name='community_pins')
    op.drop_index(op.f('ix_community_pins_community_id'), table_name='community_pins')
    op.drop_table('community_pins')
    # ### end Alembic commands ###
