"""Add community management features

Revision ID: b75a45911c77
Revises: 50988ffb0347
Create Date: 2025-11-23 22:50:31.220595

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'b75a45911c77'
down_revision: Union[str, Sequence[str], None] = '50988ffb0347'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('communities', sa.Column('owner_id', sa.UUID(), nullable=False))
    op.add_column('communities', sa.Column('rules', sa.Text(), nullable=True))
    op.create_index(op.f('ix_communities_owner_id'), 'communities', ['owner_id'], unique=False)
    op.create_foreign_key(None, 'communities', 'users', ['owner_id'], ['id'], ondelete='CASCADE')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'communities', type_='foreignkey')
    op.drop_index(op.f('ix_communities_owner_id'), table_name='communities')
    op.drop_column('communities', 'rules')
    op.drop_column('communities', 'owner_id')
    # ### end Alembic commands ###
